### ISSUE TITLE
remove command that build symfony kernel from composer.json

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#1002] opened 2019-05-07 12:19 UTC
Command `composer install` is usually called before we have an application ready (database, redis, ... are not ready yet). But now, `post-install-cmd` and `post-update-cmd` commands calls command `Shopsys\FrameworkBundle\Command\ComposerScriptHandler` that build symfony kernel. 

Because of this, we have in our project some hacks (#988, FallbackCacheFactory).

This command only checks if `domains_urls.yml` file exists and if doesn't, it will create that.  
Probably we can call that command as phing target after all containers are started. It will allow us to remove that hacks and we will have fewer problems with that in the future.

**Comment by henzigo** [comment] 2019-11-03 18:03
open it

**Comment by pk16011990** [comment] 2020-03-03 05:05
remove stale label

**Comment by grossmannmartin** [comment] 2020-03-23 21:22
Hi @henzigo,
thank you for the issue. 

On the current master branch, the `Shopsys\FrameworkBundle\Command\ComposerScriptHandler` no longer exists, but I assume this class is not the cause of a problem. 

Do I understand properly, the main issue here are commands executed after composer install (update) that needs working connections (Redis, for example)?

I think, removal of `shopsys:domains-urls:configure` from composer will not be enough, because the main problem here is running any Symfony command.

currently, we have 
```
"shopsys:domains-urls:configure": "symfony-cmd",
"ckeditor:install --clear=skip --release=full --tag=4.5.11": "symfony-cmd",
"cache:clear --no-warmup": "symfony-cmd",
```

and any of those commands will fail without `fallbackCacheFactory` with Redis disabled.

**Comment by pk16011990** [comment] 2020-03-24 07:37
I see still problem... All this scripts (`shopsys:domains-urls:configure` etc...) needs builded container and it can cause fatal, because cache is cleared as last.

FInally the biggest paradox is: symfony command `cache:clear` needs container, but container can be broken and it needs clear cache.

In my opinion clearing of cache should be cleared without symfony command - eg by phing target with cmd command...

**Comment by grossmannmartin** [comment] 2020-04-22 16:05
may be resolved with #1606 (updated version of snc/redis-bundle)

**Comment by pk16011990** [comment] 2020-04-23 05:51
Nope, please read my previous message...

It is necessary clear cache (not by Symfony command) before any symfony command. `composer.json`'s auto-scripts in project-base does not do it...

**Comment by grossmannmartin** [comment] 2020-05-06 08:57
I see. I created #1820 to clear cache first and with combination with #1606 I believe this issue is solved.
What do you think?

**Comment by pk16011990** [comment] 2020-05-06 11:57
yes, #1820 solves it :) good job :+1:

**Comment by henzigo** [comment] 2020-07-20 08:27
Hello @TomasLudvik this seems to be already solved. What do you think?

**Comment by TomasLudvik** [comment] 2020-07-21 06:03
I agree @henzigo, closing

**Closed by TomasLudvik** 2020-07-21 06:03 UTC
