### ISSUE TITLE
Ajax product filter doesn't work after submit product filter form with empty results

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1553] opened 2019-12-17 14:11 UTC
### What is happening

1. Go to category TV, audio (/tv-audio/)
2. Filter by price to filter empty result (You should see message: "No results matching filter")
3. Click in filter on button "View result"
4. It submits product filter form
5. Ajax filter doesn't work anymore and non-filterable options are not disabled
### Expected result

1. ajax filtering works
2. button "View result" do not submit filter form and scroll to message about empty search result
3. filter options are disabled

**Comment by pk16011990** [comment] 2020-02-08 12:48
I can't reproduce it. Can you confirm it? What kind of browser do you use?

**Comment by grossmannmartin** [comment] 2020-04-26 07:46
On Safari and the current master I cannot reproduce

**Comment by s3tezsky** [comment] 2020-08-07 08:16
The behavior could not be reproduced. I am closing this issue. If it is still relevant please reopen it.

**Closed by s3tezsky** 2020-08-07 08:16 UTC
