### ISSUE TITLE
Uploading image with a large extension falls to error 500

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#859] opened 2019-02-21 10:24 UTC
### What is happening
Slider on main page: Uploading image with a large extension eg xxx.PNG falls to error 500. The same problem is in advertising system. Probably it will do everywhere. (Reported by Patrik Bajer)

**Comment by simara-svatopluk** [comment] 2019-02-25 15:12
### Expected behavior
* warn/stop user before uploading by HTML/JS
* catch exception and convert it into error message

**Comment by grossmannmartin** [comment] 2019-03-04 07:35
Hi @PetraPiprekova, thanks for reporting. 

I checked the issue and I was unable to reproduce it. It's possible it was solved in #869 or #851.
Can you please try and confirm if the problem persists or it's already solved?

Thanks

**Comment by PetraPiprekova** [comment] 2019-03-04 11:30
Hi Martin, good job! Now it works.

**Comment by grossmannmartin** [comment] 2019-03-04 11:42
That's awesome :) Closing the issue then.

**Closed by grossmannmartin** 2019-03-04 11:42 UTC
