### ISSUE TITLE
PHP Fatal error:  Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by qualeo** [shopsys/shopsys#2432] opened 2022-04-29 22:24 UTC
## Describe the bug
**Fatal Error**
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /var/www/html/packages/framework/src/Component/Domain/Config/DomainsConfigDefinition.php on line 22 and at least 1 expected in /var/www/html/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
```

**Stack trace**
```
Stack trace:
#0 /var/www/html/packages/framework/src/Component/Domain/Config/DomainsConfigDefinition.php(22): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /var/www/html/vendor/symfony/config/Definition/Processor.php(46): Shopsys\FrameworkBundle\Component\Domain\Config\DomainsConfigDefinition->getConfigTreeBuilder()
#2 /var/www/html/packages/framework/src/Component/Domain/Config/DomainsConfigLoader.php(136): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(Shopsys\FrameworkBundle\Component\Domain\Config\DomainsConfigDefinition), Array)
#3 /var/www/html/packages/framework/src/Component/Domain/Config/DomainsConfigLoader.php(34): Shopsys\FrameworkBundle\Component\Domain\Config\DomainsConfigLoader->getProcessedConfig('/var/www/html/p...', Object(Shopsys\FrameworkBundle\Component\Domain\Config\DomainsConfigDefinition))
#4 /var/www/html/packages/framework/src/Component/Domain/DomainFactory.php(38): Shopsys\FrameworkBundle\Component\Domain\Config\DomainsConfigLoader->loadDomainConfigsFromYaml('/var/www/html/p...', '/var/www/html/p...')
#5 /var/www/html/project-base/var/cache/test/ContainerXxl5Wrt/srcApp_KernelTestContainer.php(1170): Shopsys\FrameworkBundle\Component\Domain\DomainFactory->create('/var/www/html/p...', '/var/www/html/p...')
#6 /var/www/html/project-base/var/cache/test/ContainerXxl5Wrt/srcApp_KernelTestContainer.php(1952): ContainerXxl5Wrt\srcApp_KernelTestContainer->getDomainService()
#7 /var/www/html/vendor/symfony/dependency-injection/Container.php(422): ContainerXxl5Wrt\srcApp_KernelTestContainer->getPrezentDoctrineTranslatable_ListenerService()
#8 /var/www/html/vendor/symfony/dependency-injection/Argument/ServiceLocator.php(42): Symfony\Component\DependencyInjection\Container->getService('services', 'prezent_doctrin...', 'getPrezentDoctr...', false)
#9 /var/www/html/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php(173): Symfony\Component\DependencyInjection\Argument\ServiceLocator->get('prezent_doctrin...')
#10 /var/www/html/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php(103): Symfony\Bridge\Doctrine\ContainerAwareEventManager->initializeSubscribers()
#11 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(223): Symfony\Bridge\Doctrine\ContainerAwareEventManager->hasListeners('loadClassMetada...')
#12 /var/www/html/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(391): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#13 /var/www/html/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(260): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Shopsys\\Framewo...')
#14 /var/www/html/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(147): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Shopsys\\Framewo...')
#15 /var/www/html/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php(64): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata()
#16 /var/www/html/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(97): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/var/www/html/p...')
#17 /var/www/html/vendor/symfony/http-kernel/Kernel.php(631): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/var/www/html/p...')
#18 /var/www/html/vendor/symfony/http-kernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#19 /var/www/html/project-base/src/Kernel.php(48): Symfony\Component\HttpKernel\Kernel->boot()
#20 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(169): App\Kernel->boot()
#21 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#22 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/project-base/bin/console(48): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#24 {main}
  thrown in /var/www/html/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
```

**Exit Code & Message**
```
> BUILD FAILED
/var/www/html/packages/framework/build.xml:917:85: Task exited with code 255

Total time: 2.1580 seconds
```

### To Reproduce
1. `git clone git@github.com:shopsys/shopsys.git` (HEAD: 6197c7d487c954d27eeaf8f6b57c4d52498a080b)
1. `cd shopsys`
1. `git checkout -b installation master`
1. `cp docker/conf/docker-compose.yml.dist docker-compose.yml`
1. `vi docker-compose.yml`
    1. _modify `php-fpm.build.args.www_data_uid` to match output of `$(id -u)`_
    1. _modify `php-fpm.build.args.www_data_gid` to match output of `$(id -g)`_
1. `docker-compose up -d --build`
1. `docker exec -it shopsys-framework-php-fpm bash`
    1. `composer install`
    1. `php phing db-create`
    1. `php phing test-db-create`

### Expected behavior
`php phing test-db-create` (run inside of ` shopsys-framework-php-fpm` container) executes fully and successfully.

### Environment (please complete the following information)
 - OS: `Ubuntu 21.10`

### Additional context
Followed installation instructions as documented at:
- https://docs.shopsys.com/en/latest/installation/installation-using-docker-linux/#option-2 (Option 2)
- https://docs.shopsys.com/en/latest/installation/installation-using-docker-application-setup/

**Comment by RobinDvorak** [comment] 2022-04-30 09:23
Hello, 
there is a bug at the moment, and `composer install` doesn't install correct versions of packages. Rollback your changes in https://github.com/shopsys/shopsys/pull/2433, connect to container and run `composer update`. Correct versions of packages will be installed and build will finish correctly.

**Comment by grossmannmartin** [comment] 2022-05-16 05:40
Hi, in symfony/flex 1.18.7 was fixed the underlying issue. 
The problem you encounter is caused by incorrect package versions installed as Robin mentioned. 

Although the changes in the TreeBuilder may work, we cannot guarantee the whole application will work correctly with newer versions of some symfony libraries and I don't want to make a false feeling of safety here.

I suggest updating symfony/flex to the mentioned version, this should fix the problem. 

We plan to update Symfony packages soon, don't worry.

**Closed by grossmannmartin** 2022-05-16 05:40 UTC
