### ISSUE TITLE
Upgrade commerceguys/intl to ^1.0.0

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#529] opened 2018-10-17 05:29 UTC
### What is happening
We require `commerceguys/intl` in `0.7.4`, and the package evolved into `1.0.1`, we should upgrade it.

### Expected result

`commerceguys/intl` is required in version `^1.0.0`

**Comment by boris-brtan** [comment] 2018-10-17 05:58
in the annotation there is this commit message
```
composer.json: require commerceguys/intl in specific version 0.7.4  - in July 2016 a new Belarusian ruble was introduced, with a new code, at a rate of 1 BYN = 10000 BYR - in the new 0.7.5 version of the intl package, support for BYR was dropped - the list of supported currency codes is covered by a unit test so it was easy to spot
```

**Comment by simara-svatopluk** [comment] 2018-10-17 06:00
Ok... what it means for upgrading to version 1?

**Comment by PetrHeinz** [comment] 2018-10-17 08:11
Closing as duplicate of #164

**Closed by PetrHeinz** 2018-10-17 08:11 UTC
