### ISSUE TITLE
ProductPicker looses GET parameters when filter is used

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1205] opened 2019-07-15 12:49 UTC
### What is happening
There are three GET parameters used to set some behavior in ProductPicker - `parentInstanceId`, `allowMainVariants` and `allowVariants`. These are lost when filter is used.

To try this go to admin and edit some order. Choose add product. ProductPicker appears and there is main variant 32PFL4400 that you cannot choose. Add this name to Quick search, click on Search button and now you can choose 32PFL4400 (even it fails with error, but the button is there).

### Expected result
GET parameters are persisted during filtering in ProductPicker.

**Comment by vitek-rostislav** [comment] 2019-07-16 12:55
Duplicate of https://github.com/shopsys/shopsys/issues/1187

**Closed by vitek-rostislav** 2019-07-16 12:55 UTC
