### ISSUE TITLE
Elasticsearch index settings in JSON violates DRY

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#937] opened 2019-04-09 05:36 UTC
### What is happening
Elasticsearch has configuration in JSON files (and in wierd filepath, see #936) and in my opinion it violates DRY and it creates chance to make mistake.

Search logic in `Shopsys\FrameworkBundle\Model\Product\Search\ProductElasticsearchRepository` needs specific fields in Elasticsearch index settings. This fields are same for all domains in stable version, but JSON files with configuration are divided into separated files for each domain. 
I understand that each domain can have different locale, but It is solvable in PHP, but not in JSON...I think.

### Expected result
Changes fields for Elasticsearch search do not need to edit more configurations if it is possible. (It is not case for singledomain and for field specific for selected languages...)

**Comment by simara-svatopluk** [comment] 2019-04-29 06:05
You are right, elastic config violates DRY. That is the only disadvantage of configs in JSONs if I understand correctly.

Advantages (over configuration in PHP)
* the PHP configuration is unreadable... full of `if` and `foreach`. JSON configuration is perfectly readable
* it is impossible to copy-paste PHP configuration to HTTP client and test/try elastic configuration. You have to dump it somehow first and then test/try it. JSON configuration is easily copy-paste-able
* JSON configuration is easy to change as it is just a JSON for each domain. If we would have "common fields in common configuration" it would be difficult to change one field for only one domain

**Comment by pk16011990** [comment] 2019-05-03 11:53
Thanks for your point of view.

First and second point can be solved by dumping configuration (eg. via command) and unreadable depends...

The third point is misunderstand this issue I think... It is possible (by `if` from first point)

**Comment by simara-svatopluk** [comment] 2019-05-06 06:48
You suggested to move the configuration to PHP. I've seen the PHP implementation in one of Shopsys projects and... my point of view:
* I understand Elasticseach, PHP and JSONs, when I see an index definition in JSON, I understand it.
* When I saw the definition in PHP - couple of methods calling each other, iterations, it took me a long time to understand just the program flow, and still I wasn't able to understand the configuration itself without dumping it.
  * So the PHP configuration is not readable for me
  * Less usable
  * Difficult to change (as it is difficult to spot the part I have to change)

Too much added difficulties and problems that benefits only in
* no DRY violation
* no need to do the same change twice (but the change itself is easy)

If you still disagree and you think that PHP configuration is great, please paste it here so we can argue concretely

**Comment by pk16011990** [comment] 2019-05-17 14:51
I'm disappointed...

No, I didn't suggest move the configuration to PHP. I wrote my opinion about DRY violation, and I think that configuration in PHP doesn't have this problem. I wrote only expected result without any mention about PHP.

You described some "problems" with configuration in PHP, I tried find some solution for this. And few days after this conversations was created #990 with "DRY violation is sometimes OK, for example in Elasticsearch configuration " with explaining that JSON is ok. I think that It isn't about format (JSON) in this case. Should I understand that this is not a problem and we can close this issue?

I'll try to describe more of what DRY violations can cause.
If developer forgets to modify the configuration for a domain, the searching on that domain does not work as expected. Developer doesn't have to forget, it can be just a typo. And Elasticsearch doesn't have to return an error, it just doesn't return the correct result. There are no tests for this (It can solve consequence, not cause).

If you want to solve the advantages of the format (JSON): If developer wants a dynamic configuration for Elasticsearch for user-specified synonyms (without using a definition file), this requires overloading of `ElasticsearchStructureManager` and the JSON configuration needs to be changed after loaded from file. Then copy-paste this configuration is useless without dump. and real configuration contains something what doesn't exist definition (synonyms). I have real example from project developers  on private project...

So, according to framework developers, is this issue a problem? I don't want to fight but give feedback based on my experiences. Unfortunately I do not see interest (eg. #990). If not, I no longer want to discusst and you can close it.

**Comment by simara-svatopluk** [comment] 2019-05-20 05:59
That's sad you are disappointed and don't see an interest because I have a need to explain what is going on.

> No, I didn't suggest move the configuration to PHP.

In the issue description you've written

> I understand that each domain can have different locale, but It is solvable in PHP, but not in JSON...I think.

I understood this as suggesting PHP and my responses were based on this assumption. Maybe I understood it wrongly but you didn't tell me it until now. And now is the first time I can do anything about it.

---
> Should I understand that this is not a problem and we can close this issue?

#990 doesn't close this issue. If we agree that duplication in elastic JSON configuration is a problem, we'll remove the example from our [Code Quality Principles](https://github.com/shopsys/shopsys/blob/master/docs/contributing/code-quality-principles.md).

---
> If developer forgets to modify the configuration for a domain, the searching on that domain does not work as expected.

You are right. If developer forgets something, the result is not as intended. This is not a problem according to me. But if you think SSFW should prevent developer from such mistakes, then this is a valid argument.

---

> If you want to solve the advantages of the format (JSON).... I have real example from project developers on private project...

This is a different argument. If you have a use case that is difficult to achieve, then this is a valid argument and we may do something about it.

---
> So, according to framework developers, is this issue a problem?

Well, the Coding Quality Principles went through standard PIA, development, CR and BV. So 3 developers and product owner had to understand the example for DRY. What more - these are principles that we ageed to keep during development and CR, so all SSFW developer saw this example and no one (as far as I know) was against this example. Based on these facts I assume this example is correct according to SSFW developers.

---

> I don't want to fight but give feedback based on my experiences

You are changing topic of this issue. I read the issue carefully and originally you were complaining about

> in my opinion it violates DRY and it creates chance to make mistake

And now you are giving real work feedback - how it is difficult to extend. That is a different issue.

---

I won't close this issue, it's up to your decision. It's up to you whether you have a will to continue the conversation.

**Comment by pk16011990** [comment] 2019-05-20 16:22
Yes, I don't want disccuss about it any more now. 

#990 created few days after this issue is a message for me, that It's ok in this exact case. And your argue about PIA, CR, BV and 3 developers and PO is fair. If you want, then close it.

**Closed** 2019-05-21 05:13 UTC
