### ISSUE TITLE
PageInfo in paginated FEAPI results returns wrong has*Page field

### ISSUE THREAD

**Issue by s3tezsky** [shopsys/shopsys#2252] opened 2021-03-02 09:41 UTC
## Describe the bug

In paginated results (e.g. articles) in frontend API when you query for `pageInfo` field the `hasPreviousPage` is always `false`.

Also in query `products` there is returned alway `true` for `pageInfo.hasNextPage`.

### To Reproduce
1. Enable FEAPI in your app.
2. Get paginated products for last few items.
3. See there is
3.1. `pageInfo.hasPreviousPage` = `false`  which is wrong
3.2. `pageInfo.hasNextPage` = `true`  which is wrong too

### Expected behavior

The `pageInfo` object returns correct information about pagination.

**Comment by s3tezsky** [comment] 2021-03-11 09:52
I have raised some questions right in https://github.com/overblog/GraphQLBundle/pull/824 because the problem is in that package. Or we lack some informations about it which are hard (or imposible) to find.

**Comment by s3tezsky** [comment] 2023-06-23 08:31
FYI: This bug should be already fixed in https://github.com/overblog/GraphQLBundle.

**Comment by grossmannmartin** [comment] 2023-08-17 09:14
@s3tezsky Thanks for the info 👍 

I tried it on the current 13.0 branch, and the issue is truly resolved. Closing then

![Snímek obrazovky 2023-08-17 v 11 13 28](https://github.com/shopsys/shopsys/assets/1177414/372217f6-b921-41db-9ea2-a4fe93c267aa)

**Closed by grossmannmartin** 2023-08-17 09:14 UTC
Labels: Bug, Status: on hold, Status: info needed
