### ISSUE TITLE
ProductFilterRepository - error in queryBuilder (addOrExtendJoin)

### ISSUE THREAD

**Issue by HakimFractal** [shopsys/shopsys#997] opened 2019-05-06 12:36 UTC
### What is happening
[Semantical Error] line 0, col 584 near ‘pcp WITH pcp.product’: Error: ‘pcp’ is already defined.

Nothing special about my settings

Problem is caused by extended ProductCalculatedPrice model. Function addOrExtendJoin in ProductFilterRepository checks ShopBundle/ProductCalculatedPrice against Framework/ProductCalculatedPrice. 

### Expected result

There should be some class resolver as you have on other places in code, or there should be used interface.

**Comment by TomasLudvik** [comment] 2019-09-04 07:48
Hello @HakimFractal, I am trying to reproduce your problem. I have extended `ProductCalculatedPrice` in ShopBundle, but I am not getting this error. Can you provide me with steps necessary to reproduce this error? Thank you.

**Comment by PetrHeinz** [comment] 2019-09-09 08:15
The root cause is that `QueryBuilderExtender` doesn't use `EntityNameResolver` when it 
detects whether the join was already used (see line 28 in `v7.3.2`): https://github.com/shopsys/shopsys/blob/aef43bab59ad65d8f0cfecd80b563ab3a91c35a4/packages/framework/src/Component/Doctrine/QueryBuilderExtender.php#L20-L32

---

This could be nicely automatically tested using unit / functional tests. It could assert whether the join will be added when `addOrExtendJoin` is called multiple times with provided `EntityNameResolver`. The `QueryBuilder` that is passed into the method can be mocked to assert specific method calls.

**Comment by s3tezsky** [comment] 2020-03-08 13:27
Hello @HakimFractal, this issue should be closed soon by merging #1391

**Comment by grossmannmartin** [comment] 2020-04-25 15:39
resolved with #1391

**Closed by grossmannmartin** 2020-04-25 15:39 UTC
Labels: Bug
