### ISSUE TITLE
Expand instructions how to add new locale in docs

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1003] opened 2019-05-07 13:23 UTC
### What is happening
When I want to create a new domain with a new language there are [instructions in the documentation](https://github.com/shopsys/shopsys/blob/master/docs/introduction/how-to-set-up-domains-and-locales.md#36-locale-in-administration).

But if it is a new language like Russia there are no information that I also need to edit [localization.php file](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Localization/Localization.php). 

### Expected result
In docs, there should be information about the necesity of changes in the Localization.php file when using a new language.

**Comment by TomasLudvik** [comment] 2019-05-20 12:19
This looks like duplicate of #934

**Comment by vitek-rostislav** [comment] 2019-07-02 10:09
closed by https://github.com/shopsys/shopsys/pull/1004

**Closed by vitek-rostislav** 2019-07-02 10:09 UTC
Labels: Documentation :book:
