### ISSUE TITLE
Change the default timezone causes tests failing

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1035] opened 2019-05-17 06:30 UTC
I would like to have the same timezone in development mode on local PC as well as in production mode on production server. If I change default timezone, application fail the tests.
### What is happening

1. Change application timezone to Europe/Prague in https://github.com/shopsys/shopsys/blob/master/project-base/docker/php-fpm/php-ini-overrides.ini#L1
2. Change application timezone to Europe/Prague in
https://github.com/shopsys/shopsys/blob/master/project-base/docker/postgres/postgres.conf#L12 and
https://github.com/shopsys/shopsys/blob/master/project-base/docker/postgres/postgres.conf#L8
3. Run tests
4. Functional tests failed. I have to edit line https://github.com/shopsys/shopsys/blob/master/project-base/tests/ShopBundle/Functional/PersonalData/Resources/test.xml#L37 and set the proper date

### Expected result

If I change the timezone, application will pass the tests.

**Comment by boris-brtan** [comment] 2019-07-03 08:51
hello, do you have already fix ? We could push it further.

**Comment by malyMiso** [comment] 2019-07-29 15:00
We don't have any fix yet. We solved it in our project only, by editing date in `test.xml`. 
@vitek-rostislav maybe it would be fine to mention this issue in installation instruction, until it will be fixed. If someone change application default timezone, he probably needs to edit date `test.xml`, due to known issue.

**Comment by vitek-rostislav** [comment] 2019-08-09 10:47
Hi @malyMiso - we already have a user story for resolving proper work with timezones that should cover this problem as well. 

TBH, not sure, where to put such "random" information in docs - all the installation guides, docker, and native-installation troubleshooting, ...

I believe this issue itself can help people who run into the same problem.
I will try to push the user story so the problem is resolved ASAP :wink:

**Comment by pk16011990** [comment] 2020-02-04 23:28
Is it not solved in the #1343?

**Comment by grossmannmartin** [comment] 2020-04-25 15:41
#1343 helps prevent the problem as it's recommended to always use UTC on the server.
Changing timezone in Dockerfile still cause the test to fail.

**Comment by s3tezsky** [comment] 2020-07-17 09:23
Hello @malyMiso is there any reason to set different timezone than UTC?

I am just thinking loud and want to hear any reason to make this change. I can imagine fixing this test will open doors to changing timezone of PHP which may lead to unwanted results.

We are informing about default UTC [in our documentation](https://github.com/shopsys/shopsys/blob/master/docs/introduction/start-building-your-application.md#set-up-timezone-to-display-dates)
> Dates are internally stored in UTC. That supports portability and eases integration with other systems.

I see two options which could be done to fix this test and prevent time zone issues:

1. We should force the UTC as the only valid setting for project based on shopsys framework (cannot imagine what possibly could go wrong to set anything else). Maybe there could be a check?

2. In case we want to be more open we should think about reflecting server configuration. Any date time which comes from application (any particular `new \DateTime`, and some others) should be transformed to UTC based on datetime zone configuration of the server.

---

I am voting for closing this issue.

**Comment by TomasLudvik** [comment] 2020-07-17 09:25
I agree with @s3tezsky and part 1.

**Comment by grossmannmartin** [comment] 2020-07-17 09:45
UTC should be, from my point of view, the only valid choice for server configuration, and dates should be presented to the user in proper timezone with a solution introduced in #1343. 

I think this issue was raised before 1343 was done, so I understand the need before. 

If needed, please create a PR to solve this problem. For now, I would recommend keeping server settings in UTC and in case of migrating an old project with server set to different timezone, to fix the test manually.

**Comment by TomasLudvik** [comment] 2020-07-17 11:50
This issue has been solved in #1343. If developers decide to have different timezone than UTC, they have to update tests as well. Closing.

**Closed by TomasLudvik** 2020-07-17 11:50 UTC
