### ISSUE TITLE
Admin: can't choose each choice of form in DEVELOPMENT ENV with opened symfony bar

### ISSUE THREAD

**Issue by thirdknown** [shopsys/shopsys#604] opened 2018-11-15 13:41 UTC
### What is happening
Admnistration: If I add new group to form type extension with ChoiceType to the end of builder, some choices are not visible, so admin can't choose them.

![screenshot from 2018-11-15 14-33-44](https://user-images.githubusercontent.com/25673907/48556451-4275bd00-e8e4-11e8-9d5f-0d0d18c02782.png)

### Expected result
Admin can choose each value.

**Comment by PetrHeinz** [comment] 2018-11-15 15:48
Hi @thirdknown and thanks for the reported issue.

It looks like a duplicate of a previously closed #139. I've quickly checked how it is behaving on current master, and it looks like it's working (b23274b84, section Products >  Categories >  Editing category - Electronics with demo data, viewed on Google Chrome 70.0.3538.102, Ubuntu 18.04.1 LTS 64-bit):

![image](https://user-images.githubusercontent.com/10008612/48564059-f92e6900-e8f5-11e8-9454-365ce02a3f5e.png)

Can you provide clear steps to reproduce, so we can track this down, please?

**Comment by boris-brtan** [comment] 2018-11-23 07:58
seems like we found a problem. the correct image of problem should be:
![image](https://user-images.githubusercontent.com/39240194/48932770-ddcaeb80-eefd-11e8-89ee-3cea8cc9e823.png)
So only when you have opened symfony bar because it doesnt count with another fixed bar but if you click on X it is OK

**Comment by thirdknown** [comment] 2018-11-23 08:06
Thank you.
I think it should be repaired because of better feeling of SSFW consumer's developers.

**Comment by topolanekmartin** [comment] 2018-11-23 09:33
Thank you @PetrHeinz for tip.

**Comment by PetrHeinz** [comment] 2018-11-23 09:41
@topolanekmartin: It gave me an idea whether it would be a good idea to have a JS component (view.js?) that could provide the upper / lower offset of current view (counting with fixed headers and footers both in admin and frontend). I think it might be pretty useful for many things when implementing javascript features.

**Comment by topolanekmartin** [comment] 2018-11-23 10:50
@PetrHeinz I will consider it during implementation :) But I have same opinion. Something like that could be useful.

**Comment by boris-brtan** [comment] 2018-11-23 14:14
now we with @topolanekmartin found out that it is problem in changes that you did @thirdknown. @topolanekmartin will contact you with more info

**Comment by boris-brtan** [comment] 2018-11-24 09:16
From the programming perspective best solution would be during extension of `CategoryForm` to put fields before `pluginGroup` there are some examples how to rearrange some already assigned groups or elements in [this PR](https://github.com/shopsys/demoshop/pull/8/files#diff-5)

**Closed** 2018-11-30 06:50 UTC
Labels: Design & Apperance, Easy Pick :baby_chick:, Status: in implementation
